server:
  port: 8083

spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: 'Ycx541353060'
    url: jdbc:mysql://47.100.253.34:3306/yyy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  #datasource:
  #  type: com.alibaba.druid.pool.DruidDataSource
   # driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://47.100.253.34:5432/postgres
   # username: postgres
   # password: 541353060
  redis:
    host: 47.100.253.34 # Redis服务器地址,注意配置一定要在spring下面
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 541353060 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

level:
  com:
    hl:
      magic: trace
logging:
  config: /opt/yuchenxi/apps/config/logback.xml
  level:
    com.example.demo.dao: DEBUG


mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.example.demo.vo


